- name: install LAMP Stack
  hosts: azure
  become: true
  become_user: root
  gather_facts: true

- name: Include Pip
  import_playbook: pip.yml

- name: Include Apache
  import_playbook: apache.yml

- name: Include MySQL
  import_playbook: mysql.yml
